# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d0aaadba219e5910f1d5a27b694bf08ee02723cb6a13b2861eda0444ca3c99e456bdfec248c6effeaa60916b720bcfe418540e9b5bb858af33f61aebfdf1a24

test:
  secret_key_base: 14ebf15db2990acb998406e13f1f84c9960291d22e60949c6268035e5827c2b9cf0412a10ebc7d7a175ce97da5d151f7b951e0fcec74bbfe3e2f6c254c200ca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
